apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: notify-worker
  namespace: urlmap
spec:
  backendType: gcpSecretsManager
  projectId: $PROJECT
  data:
    - key: SLACK_URL
      name: slack-url
      version: latest
